%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    Y:\UserData\Maccine\Data\Uploads\Decrypt\2012-02-22\NSB_Output\NSB_SpectralAnalysis_2162_1_SpectralData.csv
%    Worksheet: NSB_SpectralAnalysis_2162_1_Spe
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2012/05/05 16:51:49

function [OutMat] = NSB_readNSBoutput(fn)
%% Import the data
[~, ~, raw] = xlsread(fn,'A2:IV139');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};


%% Replace specified string with NaN
R = cellfun(@(x) ischar(x) && strcmp(strtrim(x),'NaN') ,raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
OutMat = cell2mat(raw);
